version: '3.7'

services:
  dev: &dev
    container_name: backend_dev
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.development
    volumes:
      - ./packages/backend:/usr/src/app
    ports:
      - 8080:8080
    command: sh -c "yarn && yarn start:dev"
    networks:
      - backend-network
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mymonomoney-localdocker

  debug:
    <<: *dev
    container_name: backend_debug
    command: sh -c "yarn && yarn start:debug"
    ports:
      - 8080:8080
      - 9229:9229

  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    networks:
      - backend-network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mymonomoney-localdocker
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.0-alpine
    command: >
      --requirepass redis
    ports:
      - 6379:6379
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  pgdata:
